nc_counties_list = ['Alleghany County',
                    'Ashe County',
                    'Avery County',
                    'Buncombe County',
                    'Burke County',
                    'Caldwell County',
                    'Cherokee County',
                    'Clay County',
                    'Graham County',
                    'Haywood County',
                    'Henderson County',
                    'Jackson County',
                    'Macon County',
                    'Madison County',
                    'McDowell County',
                    'Mitchell County',
                    'Polk County',
                    'Rutherford County',
                    'Stokes County',
                    'Surry County',
                    'Swain County',
                    'Transylvania County',
                    'Watauga County',
                    'Wilkes County',
                    'Yancey County'
                ]